Dogbert2/Models/ProjectViewModel.cs
using System.Collections.Generic;
using Dogbert2.Core.Domain;
using UCDArch.Core.PersistanceSupport;
using UCDArch.Core.Utils;
using System.Linq;

namespace Dogbert2.Models
{
    /// <summary>
    /// ViewModel for the Project class
    /// </summary>
    public class ProjectViewModel
    {
        public Project Project { get; set; }
        public Workgroup Workgroup { get; set; }

        public IEnumerable<StatusCode> StatusCodes { get; set; }
        public IEnumerable<PriorityType> PriorityTypes { get; set; }
        public IEnumerable<ProjectType> ProjectTypes { get; set; }
        public IEnumerable<Workgroup> Workgroups { get; set; }
        public IEnumerable<Worker> Workers { get; set; }

        public static ProjectViewModel Create(IRepository repository, string login)
        {
            Check.Require(repository != null, "Repository must be supplied");

            var worker = repository.OfType<Worker>().Queryable.Where(a => a.LoginId == login).First();

            var viewModel = new ProjectViewModel {
                Project = new Project(),
                StatusCodes = repository.OfType<StatusCode>().GetAll(),
                ProjectTypes = repository.OfType<ProjectType>().Queryable.Where(a=>a.IsActive).OrderBy(a=>a.Order).ToList(),
                PriorityTypes = repository.OfType<PriorityType>().Queryable.OrderBy(a=>a.Order).ToList(),
                Workgroups = worker.WorkgroupWorkers.Where(a=>a.Workgroup.IsActive).Select(a=>a.Workgroup).ToList(),
            };

            var workers = new List<Worker>();
            foreach (var a in viewModel.Workgroups)
            {
                workers.AddRange(a.WorkgroupWorkers.Select(b=>b.Worker).ToList());
            }
            viewModel.Workers = workers.Distinct().OrderBy(a => a.LastName).ToList();

            return viewModel;
        }
    }
}

Dogbert2/Controllers/FileController.cs
using System;
using System.Linq;
using System.Security;
using System.Web.Mvc;
using Dogbert2.App_GlobalResources;
using Dogbert2.Core.Domain;
using Dogbert2.Filters;
using Dogbert2.Models;
using Dogbert2.Services;
using UCDArch.Core.PersistanceSupport;
using MvcContrib;
using UCDArch.Web.Helpers;
using File = Dogbert2.Core.Domain.File;

namespace Dogbert2.Controllers
{
    /// <summary>
    /// Controller for the File class
    /// </summary>
    [Authorize]
    public class FileController : ApplicationController
    {
	    private readonly IRepository<File> _fileRepository;
        private readonly IRepository<Project> _projectRepository;
        private readonly IAccessValidatorService _accessValidator;

        public FileController(IRepository<File> fileRepository, IRepository<Project> projectRepository, IAccessValidatorService accessValidator)
        {
            _fileRepository = fileRepository;
            _projectRepository = projectRepository;
            _accessValidator = accessValidator;
        }

        /// <summary>
        /// Project files
        /// </summary>
        /// <param name="id">Project Id</param>
        /// <returns></returns>
        public ActionResult Index(int id)
        {
            //var fileList = _fileRepository.Queryable;

            var project = _projectRepository.GetNullableById(id);

            if (project == null)
            {
                Message = string.Format(Messages.NotFound, "project", id);
                return this.RedirectToAction<ProjectController>(a => a.Index());
            }

            // validate access
            var redirect = _accessValidator.CheckReadAccess(CurrentUser.Identity.Name, project);
            if (redirect != null) return redirect;

            ViewBag.ProjectId = id;

            return View(project.Files);
        }

        //
        // GET: /File/Create
        public ActionResult Create(int id)
        {
            var project = _projectRepository.GetNullableById(id);

            if (project == null)
            {
                Message = string.Format(Messages.NotFound, "project", id);
                return this.RedirectToAction<ProjectController>(a => a.Index());
            }

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

			var viewModel = FileViewModel.Create(Repository, project);
            viewModel.Files.Add(new File());
            return View(viewModel);
        } 

        //
        // POST: /File/Create
        [HttpPost]
        public ActionResult Create(int id, FilePostModel[] files)
        {
            var project = _projectRepository.GetNullableById(id);

            if (project == null)
            {
                Message = string.Format(Messages.NotFound, "project", id);
                return this.RedirectToAction<ProjectController>(a => a.Index());
            }

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

            for (var i = 0; i < files.Count(); i++)
            {
                var postedFile = files[i];

                if (postedFile.File != null && postedFile.File.ContentLength > 0)
                {
                    var newFile = new File();
                    AutoMapper.Mapper.Map(postedFile, newFile);
                    newFile.Project = project;

                    ModelState.Clear();
                    newFile.TransferValidationMessagesTo(ModelState);

                    if (ModelState.IsValid)
                    {
                        _fileRepository.EnsurePersistent(newFile);
                    }
                    else
                    {
                        Message = string.Format("There was a problem saving {0}", newFile.FileName);
                    }
                }
            }

            return this.RedirectToAction(a => a.Index(id));
        }

        //
        // GET: /File/Edit/5
        public ActionResult Edit(int id)
        {
            var file = _fileRepository.GetNullableById(id);

            if (file == null) return this.RedirectToAction<ProjectController>(a=>a.Index());

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, file.Project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

			return View(file);
        }
        
        //
        // POST: /File/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FilePostModel file)
        {
            var fileToEdit = _fileRepository.GetNullableById(id);

            if (fileToEdit == null) return this.RedirectToAction<ProjectController>(a => a.Index());

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, fileToEdit.Project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

            // no file update, preserve old information
            if (file.File == null)
            {
                // save the old values
                var contents = fileToEdit.Contents;
                var type = fileToEdit.ContentType;
                var name = fileToEdit.FileName;

                AutoMapper.Mapper.Map(file, fileToEdit);

                // copy back in the values
                fileToEdit.Contents = contents;
                fileToEdit.ContentType = type;
                fileToEdit.FileName = name;
            }
            // file was uploaded, perform standard transfer
            else
            {
                AutoMapper.Mapper.Map(file, fileToEdit);    
            }

            if (ModelState.IsValid)
            {
                fileToEdit.LastUpdate = DateTime.Now;
                _fileRepository.EnsurePersistent(fileToEdit);

                Message = "File Edited Successfully";

                return this.RedirectToAction(a => a.Index(fileToEdit.Project.Id));
            }

            return View(fileToEdit);
        }
        
        //
        // GET: /File/Delete/5 
        public ActionResult Delete(int id)
        {
			var file = _fileRepository.GetNullableById(id);

            if (file == null) return this.RedirectToAction<ProjectController>(a=>a.Index());

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, file.Project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

            return View(file);
        }

        //
        // POST: /File/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, File file)
        {
			var fileToDelete = _fileRepository.GetNullableById(id);

            if (fileToDelete == null) return this.RedirectToAction<ProjectController>(a => a.Index());

            // validate access
            var redirect = _accessValidator.CheckEditAccess(CurrentUser.Identity.Name, fileToDelete.Project);
            if (redirect != null)
            {
                Message = "Not authorized to edit project.";
                return redirect;
            }

            var projectId = fileToDelete.Project.Id;

            _fileRepository.Remove(fileToDelete);

            Message = "File Removed Successfully";

            return this.RedirectToAction(a=>a.Index(projectId));
        }

        public FileResult Download(int id)
        {
            var file = _fileRepository.GetNullableById(id);

            // validate access
            var redirect = _accessValidator.CheckReadAccess(CurrentUser.Identity.Name, file.Project);
            if (redirect != null) throw new SecurityException("Not authorized to download file");

            return File(file.Contents, file.ContentType, file.FileName);
        }

    }


}

Dogbert2/Controllers/SrsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Web.Mvc;
using Dogbert2.Core.Domain;
using Dogbert2.Filters;
using Dogbert2.Services;
using UCDArch.Core.PersistanceSupport;

namespace Dogbert2.Controllers
{
    /// <summary>
    /// Controller for the Srs class
    /// </summary>
    [Authorize]
    public class SrsController : ApplicationController
    {
        private readonly IRepository<Project> _projectRepository;
        private readonly IRepository<File> _fileRepository;
        private readonly IAccessValidatorService _accessValidator;

        public SrsController(IRepository<Project> projectRepository, IRepository<File> fileRepository, IAccessValidatorService accessValidator)
        {
            _projectRepository = projectRepository;
            _fileRepository = fileRepository;
            _accessValidator = accessValidator;
        }

        /// <summary>
        /// Get the SRS for a project
        /// </summary>
        /// <param name="id">Project Id</param>
        /// <returns></returns>
        public FileResult Index(int id, bool draft = false)
        {
            var project = _projectRepository.GetNullableById(id);

            // validate access
            var redirect = _accessValidator.CheckReadAccess(CurrentUser.Identity.Name, project);
            if (redirect != null) throw new SecurityException("Not authorized to view file");

            var generator = new PdfService(_fileRepository, Repository.OfType<SectionType>());

            // get the srs
            var srs = generator.GeneratePdf(project, draft);

            // append the files if any
            var files = new List<byte[]>();
            files.Add(srs);
            files.AddRange(project.Files.Where(a => a.Append).Select(a=>a.Contents).ToList());

            var pdf = new byte[0];
            if (files.Count() > 1)
            {
                pdf = generator.PdfMerger(files);
            }
            else
            {
                pdf = srs;
            }

            if (draft)
            {
                pdf = generator.WatermarkPdf(pdf, "DRAFT");
            }

            return File(pdf, "application/pdf", string.Format("srs-{0}.pdf", id));
        }
    }
}

Dogbert2/Views/Project/Completed.cshtml
@model IEnumerable<ProjectWorkgroup>

@{
	ViewBag.Title = "Completed / Hidden Projects";
}

@section SubNav
{
	<ul class='navigation'>
		<li>@Html.ActionLink("Back to My Projects", "Index")</li>
	</ul>
}


<table class='dt-table nolasticon'>
	<thead>
		<tr>
			<th></th>
            <th>Workgroup</th>
            <th>Name</th>
            <th>Unit</th>
            <th>Status</th>
		</tr>
	</thead>
	<tbody>
@{ var odd = false; }
@foreach (var item in Model) {
		<tr class="@(odd ? "odd": "even")">
			<td>
				<a href='@Url.Action("Details", new {id=item.Id})'>
					<img src='@Url.Image("details.png")' />
				</a>
				<a href='@Url.Action("Edit", new {id=item.Id})'>
					<img src='@Url.Image("edit.png")' />
				</a>
			</td>

            <td>@item.Workgroup.Name</td>
            <td>@item.Project.Name</td>
            <td>@item.Project.Unit</td>
            <td>@item.Project.StatusCode.Name</td>
		
		</tr>
		odd = !odd;
}
	</tbody>
</table>

Dogbert2/Views/Project/Create.cshtml
@model ProjectViewModel

@{
	ViewBag.Title = "Create Project";
    ViewBag.NavigationKey = "Project";
}

@section SubNav
{
	<ul class="navigation">
		<li>@Html.ActionLink("Back to List", "Index")</li>
	</ul>
}

@Html.Partial("_Project")

Dogbert2/Views/Project/Delete.cshtml
@model Dogbert2.Core.Domain.Project


@{
    ViewBag.Title = "Delete Project";
    ViewBag.NavigationKey = "Project";
}

<h3>Are you sure you want to delete this?</h3>

@using (Html.BeginForm()) {
	@Html.AntiForgeryToken()

<fieldset class="display-form">
	<legend>Project</legend>
	<ul>

		<li>
			<div class="display-label">Name</div>
			<div class="display-details">@Model.Name</div>
		</li>

				<li>
			<div class="display-label">Contact</div>
			<div class="display-details">@Model.Contact</div>
		</li>

		<li>
			<div class="display-label">ContactEmail</div>
			<div class="display-details">@Model.ContactEmail</div>
		</li>

		<li>
			<div class="display-label">Unit</div>
			<div class="display-details">@Model.Unit</div>
		</li>

		<li>
			<div class="display-label">DateAdded</div>
			<div class="display-details">@String.Format("{0:g}", Model.DateAdded)</div>
		</li>

		<li>
			<div class="display-label">LastUpdate</div>
			<div class="display-details">@String.Format("{0:g}", Model.LastUpdate)</div>
		</li>

		<li>
			<div class="display-label">Workgroup(s)</div>
			<div class="display-details">@Model.WorkgroupNames</div>
		</li>
		
		<li>
			@* For the clear and submit buttons an empty label is required. Example: <label>&nbsp;</label> *@
			<div class="display-label">&nbsp;</div>
			<div class="display-details">
			<input class="button" type="submit" value="Delete" /> | @Html.ActionLink("Cancel", "Index")
			</div>
		</li>
	</ul>
</fieldset>
}

Dogbert2/Views/Project/Details.cshtml
@model Dogbert2.Core.Domain.Project


@{
    ViewBag.Title = Model.Name;
    ViewBag.NavigationKey = "Project";
}

@section SubNav
{
	<ul class="navigation">
		
            @*@if (ViewBag.PublicList == false)
            { 
                <li>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) </li>
            }*@
			
            <li>@Html.ActionLink("Glossary", "Index", "ProjectTerm", new { id = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Sections", "Index", "ProjectSection", new { id = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Requirements", "Index", "Requirement", new { id = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Use Cases", "Index", "UseCase", new { id = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Files", "Index", "File", new { id = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Tasks", "Index", "Task", new { projectId = Model.Id }, new { })</li>
            <li>@Html.ActionLink("Changes", "Index", "ChangeRequest", new {id=Model.Id}, new {})</li>

            @if (ViewBag.PublicList == false)
            { 
                <li>@Html.ActionLink("Back to List", "Index")</li>
            }
            else
            { 
                <li>@Html.ActionLink("Back to List", "Public")</li>
            }
			
		
	</ul>
}

@section AdditionalScripts
{
    <style type="text/css">
        #srs-container{text-align: center;}
    </style>
}

<fieldset class="display-form">
    <legend>Project</legend>
	<ul>

		<li>
			<div class="display-label">Complexity</div>
			<div class="display-details">@Model.Complexity</div>
		</li>

		<li>
			<div class="display-label">Deadline</div>
			<div class="display-details">@ProjectInfo.ProjectDeadline(Model)</div>
		</li>

		<li>
			<div class="display-label">Begin</div>
			<div class="display-details">@ProjectInfo.ProjectBegin(Model)</div>
		</li>

		<li>
			<div class="display-label">End</div>
			<div class="display-details">@ProjectInfo.ProjectEnd(Model)</div>
		</li>
        		
		<li>
			<div class="display-label">Contact</div>
			<div class="display-details">@Model.Contact</div>
		</li>

		<li>
			<div class="display-label">ContactEmail</div>
			<div class="display-details">@Model.ContactEmail</div>
		</li>

		<li>
			<div class="display-label">Unit</div>
			<div class="display-details">@Model.Unit</div>
		</li>

		<li>
			<div class="display-label">Date Added</div>
			<div class="display-details">@String.Format("{0:g}", Model.DateAdded)</div>
		</li>

		<li>
			<div class="display-label">Last Update</div>
			<div class="display-details">@String.Format("{0:g}", Model.LastUpdate)</div>
		</li>

				<li>
			<div class="display-label">Workgroup(s)</div>
			<div class="display-details">@Model.WorkgroupNames</div>
		</li>

        <li>
            <div class="display-label">Is Public</div>
            <div class="display-details">@(Model.IsPublic ? "Yes" : "No")</div>
        </li>

	</ul>

    <div id="srs-container">

    @if (ViewBag.AccessValidator.HasAccess(HttpContext.Current.User.Identity.Name, Model) == Dogbert2.Services.AccessLevel.Edit)
    { 
        @Html.ActionLink("Generate SRS", "Index", "Srs", new { id = Model.Id, draft = false }, new { @class = "large-btn", style = "display: inline-block;" })
        @Html.ActionLink("Generate Draft SRS", "Index", "Srs", new { id = Model.Id, draft = true }, new { @class = "large-btn", style = "display: inline-block;" })
    }
    else
    { 
        if (Model.StatusCode.Id == 'P' || Model.StatusCode.Id == 'B')
        { 
            @Html.ActionLink("Generate SRS", "Index", "Srs", new { id = Model.Id, draft = false }, new { @class = "large-btn", style = "display: inline-block;" })
        }
        else
        { 
            @Html.ActionLink("Generate SRS", "Index", "Srs", new { id = Model.Id, draft = true }, new { @class = "large-btn", style = "display: inline-block;" })
        }
    }
    </div>

</fieldset>

Dogbert2/Views/Project/Edit.cshtml
@model ProjectViewModel


@{
    ViewBag.Title = "Edit Project";
    ViewBag.HideWorkgroup = true;
    ViewBag.NavigationKey = "Project";
}

@section SubNav
{
    <ul class="navigation">
        <li>@Html.ActionLink("Details", "Details", new {Id=Model.Project.Id})</li>
        <li>@Html.ActionLink("Workgroups", "Index", "ProjectWorkgroup", new { Id=Model.Project.Id }, new { })</li>
        <li>@Html.ActionLink("Requirement Categories", "Index", "RequirementCategory", new { Id = Model.Project.Id }, new { })</li>
        <li>Actors</li>
    </ul>
}

@Html.Partial("_Project")

Dogbert2/Views/Project/Index.cshtml
@model IEnumerable<Workgroup>


@{
	ViewBag.Title = "My Projects";
    ViewBag.NavigationKey = "Project";
    ViewBag.dTable = true;
}

@section SubNav
{
	<ul class='navigation'>
        <li>@Html.ActionLink("Manage", "Manage")</li>
        <li>@Html.ActionLink("Completed", "Completed")</li>
		<li>@Html.ActionLink("Create New", "Create")</li>
	</ul>
}

@section AdditionalScripts
{
    <script type="text/javascript">

        $(function () {
            $("#tabs").tabs();
        });

    </script>
}

@if (Model.Count() == 1)
{
    // display the table only
    @Html.Partial("_ProjectTable", Model.FirstOrDefault().ProjectWorkgroups)
}
else
{ 
    // display the tabs
    @Html.Partial("_ProjectTabs", Model)
    
}

Dogbert2/Views/Project/Manage.cshtml
@model IEnumerable<Workgroup>

@{
    ViewBag.Title = "Manage Projects";
}

@section SubNav
{
	<ul class="navigation">
		<li>@Html.ActionLink("Back to My Projects", "Index", "Project")</li>
	</ul>
}

@section AdditionalScripts
{
    <script type="text/javascript" src="@Url.Script("jquery.tablednd_0_5.js")"></script>

    <script type="text/javascript">

        $(function () {

            $("#tabs").tabs();

            $("table").tableDnD({
                onDragClass: "dragging",
                onDrop: function (table, row) {
                    // re-adjust the odd, even row classes
                    $("tbody tr").removeClass("odd");
                    $("tbody tr").removeClass("even");

                    $("tbody tr:even").addClass("even");
                    $("tbody tr:odd").addClass("odd");

                    var rows = table.tBodies[0].rows;
                    var order = [];
                    $.each(rows, function (index, item) {
                        order.push($(item).data("id"));
                    });

                    var id = $("table").parents(".plist-container").data("id");

                    var url = '@Url.Action("UpdateProjectOrder")';
                    var antiForgery = $('input[name="__RequestVerificationToken"]').val();
                    $.post(url, { workgroupId: id, projectWorkgroupId: order, __RequestVerificationToken: antiForgery }, function (result) {

                        if (result == false) alert("failed to update order");

                    });
                }
            });

        });

    </script>
}

@Html.AntiForgeryToken()

@if (Model.Count() == 1)
{
    @Html.Partial("_ProjectTable", Model.FirstOrDefault().ProjectWorkgroups)
}
else
{ 
    // display the tabs
    @Html.Partial("_ProjectTabs", Model)
    
}

Dogbert2/Views/Project/Public.cshtml
@model IEnumerable<Dogbert2.Core.Domain.Project>

@{
	ViewBag.Title = "Public Projects";
}

@section SubNav
{
	<ul class='navigation'>
	</ul>
}


<table class='dt-table nolasticon'>
	<thead>
		<tr>
			<th></th>
			<th>
				Name
			</th>
            <th>
                Unit
            </th>
			<th>
                Workgroups
            </th>
            <th>
                Departments
            </th>
            <th>
				Last Update
			</th>

		</tr>
	</thead>
	<tbody>
@{ var odd = false; }
@foreach (var item in Model) {
		<tr class="@(odd ? "odd": "even")">
			<td>
				<a href='@Url.Action("Details", new { id = item.Id, publicList = true})'>
					<img src='@Url.Image("details.png")' />
				</a>
			</td>
			<td>
				@item.Name
			</td>
            <td>
                @item.Unit
            </td>
            <td>
				@item.WorkgroupNames
			</td>
			<td>
				@item.WorkgroupDepts
			</td>
			<td>
				@String.Format("{0:g}", item.LastUpdate)
			</td>		
		</tr>
		odd = !odd;
}
	</tbody>
</table>

Dogbert2/Views/Project/_ProjectTable.cshtml
@model IEnumerable<ProjectWorkgroup>

@{
    var classes = ViewBag.dTable == true ? "dt-table" : string.Empty;
    var workgroupId = Model.Count() > 0 ? Model.FirstOrDefault().Workgroup.Id : -1;
}

<div class="plist-container" data-id="@workgroupId">
<table class='@classes'>
	<thead>
		<tr>
			<th></th>

			<th>Name</th>
			<th>Contact</th>
            <th>Unit</th>
            <th>Complexity</th>
            <th>Start</th>
            <th>End</th>
			<th>Deadline</th>
            <th>Status</th>
			
            <th></th>
		</tr>
	</thead>
	<tbody>
@{ var odd = false; }
@foreach (var item in Model.Where(a=>a.Project.StatusCode.Display && !a.Project.Hide).OrderBy(a =>a.Order))
{
		<tr class="@(odd ? "odd" : "even")" data-id="@item.Id">

			<td>
				<a href='@Url.Action("Details", new { id = item.Project.Id })'>
					<img src='@Url.Image("details.png")' />
				</a>
				<a href='@Url.Action("Edit", new { id = item.Project.Id })'>
					<img src='@Url.Image("edit.png")' />
				</a>
			</td>

			<td>@item.Project.Name</td>
			<td>@item.Project.Contact</td>
            <td>@item.Project.Unit</td>
            <td>@item.Project.Complexity</td>
            <td>@ProjectInfo.ProjectBegin(item.Project)</td>
            <td>@ProjectInfo.ProjectEnd(item.Project)</td>
            <td>@ProjectInfo.ProjectDeadline(item.Project)</td>
            <td>@item.Project.StatusCode.Name</td>
				
			<td>
				<a href='@Url.Action("Delete", new { id = item.Project.Id })'>
					<img src='@Url.Image("delete.png")' />
				</a>
			</td>
		

		</tr>
		odd = !odd;
}
	</tbody>
</table>
</div>

Dogbert2/Views/Project/_ProjectTabs.cshtml
@model IEnumerable<Workgroup>

<div id="tabs">
    <ul>
        @foreach (var workgroup in Model)
        { 
            <li>
                <a href='@string.Format("#tab-{0}", workgroup.Id)'>@workgroup.Name</a>
            </li>
        }
    </ul>

    @foreach(var workgroup in Model)
    {
        <div id='@string.Format("tab-{0}", workgroup.Id)'>
            @Html.Partial("_ProjectTable", workgroup.ProjectWorkgroups)
        </div>
    }

</div>